### ISSUE TITLE
Create a diagram that describes the Greenfield workflow

### ISSUE THREAD

**Issue by davgordo** [halkyonio/assemble-architectural-decision-log#16]
As a Developer
I want a diagram that describes the Greenfield onboarding workflow
So that I can understand the steps that happen in the Greenfield onboarding workflow

Acceptance:
- Should support the UX workflow diagrams
- Each external interaction that takes place within the workflow and the target system is described
- Reviewed with the team and the teams understands the diagram

**Comment by lstewart74** [comment]
https://miro.com/app/board/uXjVPfcPnck=/?moveToWidget=3458764532723707331&cot=14

**Comment by lstewart74** [comment]
![Image](https://user-images.githubusercontent.com/13815631/189661339-4222926d-eb9e-42c0-8bd5-e44537996193.png)
